### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Cross22** [serj-lotutovici/jacoco-example#1]
I have modified local.properties to point to my SDK directory. Invoking gradle results in this error:

com.github.example.testjacoco.DummyClassTest > stuff FAILED
    java.lang.NoClassDefFoundError: org/apache/maven/artifact/ant/DependenciesTask

        Caused by:
        java.lang.ClassNotFoundException: org.apache.maven.artifact.ant.DependenciesTask

**Comment by serj-lotutovici** [comment]
### 1. Solution ###
It's a **bug** in android gradle build plugin 1.1.3.
Try running in 3 (three) steps:

`~# ./gradlew clean compileDebugSources`

`~# ./gradlew assembleDebug assembleDebugUnitTest`

`~# ./gradlew testDebug jacocoFullReport`

### 2. Solution ###

If you don't want any hassle, checkout this branch [and_gp_1.2.3](https://github.com/serj-lotutovici/jacoco-example/tree/and_gp_1.2.3]). If uses the latest plugin 1.2.3.

Just tested it runs without any problems:

`~# ./gradlew clean jacocoFullReport`

**Comment by Cross22** [comment]
Thank you for your quick response! I tried Solution #2 and that worked !
